# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37e8df7585b72fd2c4204b7dc3f2fc8c69b47f39d16fd3dfacc90dbebdd84a9af74e73c1b854ccf2c2192b099d2f6f1d9fd9b61145e9e5bef646f4f8dd3a6c48

test:
  secret_key_base: 7f13147dff013d2f5aa746a127d445f0c5953a0d49974a86ff0c433911b743945eae52c0d8f7f2662d28b839148fcb2dd0bbc2c86c085a6d4c27a4a3803aa20e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
